services:
  pacstall-deb-builder:
    build: .
    image: my-pacstall-programs-builder
    pull_policy: build
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
